version: 2

models:
  - name: raw_data
    description: "Cleaned ClinicalTrialsData"


  - name: clinical_trials
    description: "Cleaned ClinicalTrialsData"
    config:
      contract:
        enforced: false
    columns:
      - name: id
        data_type: string
        description: "The primary key for this table"
        data_tests:
          - not_null
          - unique
        constraints:
          - type: not_null
          - type: primary_key


  - name: adverse_events
    description: "Adverse Events data from clinical trials"
    config:
      contract:
        enforced: false
    columns:
      - name: id
        data_type: string
        description: "The primary key for this table"
        data_tests:
          - not_null
          - unique
          - relationships:
              to: ref('clinical_trials')
              field: id
        constraints:
          - type: not_null
          - type: primary_key


  - name: condition_browse
    description: "Browseable conditions related to the trials"
    config:
      contract:
        enforced: false
    columns:
      - name: id
        data_type: string
        description: "The primary key for this table"
        data_tests:
          - not_null
          - unique
          - relationships:
              to: ref('clinical_trials')
              field: id
        constraints:
          - type: not_null
          - type: primary_key


  - name: eligibility
    description: "Eligibility criteria for the trials"
    config:
      contract:
        enforced: false
    columns:
      - name: id
        data_type: string
        description: "The primary key for this table"
        data_tests:
          - not_null
          - unique
          - relationships:
              to: ref('clinical_trials')
              field: id
        constraints:
          - type: not_null
          - type: primary_key


  - name: large_document
    description: "Large documents related to the clinical trials"
    config:
      contract:
        enforced: false
    columns:
      - name: id
        data_type: string
        description: "The primary key for this table"
        data_tests:
          - not_null
          - unique
          - relationships:
              to: ref('clinical_trials')
              field: id
        constraints:
          - type: not_null
          - type: primary_key


  - name: participant_flow
    description: "Flow of participants through the clinical trial"
    config:
      contract:
        enforced: false
    columns:
      - name: id
        data_type: string
        description: "The primary key for this table"
        data_tests:
          - not_null
          - unique
          - relationships:
              to: ref('clinical_trials')
              field: id
        constraints:
          - type: not_null
          - type: primary_key


  - name: annotations
    description: "Annotations associated with trial data"
    config:
      contract:
        enforced: false
    columns:
      - name: id
        data_type: string
        description: "The primary key for this table"
        data_tests:
          - not_null
          - unique
          - relationships:
              to: ref('clinical_trials')
              field: id
        constraints:
          - type: not_null
          - type: primary_key


  - name: conditions
    description: "Detailed conditions related to the trials"
    config:
      contract:
        enforced: false
    columns:
      - name: id
        data_type: string
        description: "The primary key for this table"
        data_tests:
          - not_null
          - unique
          - relationships:
              to: ref('clinical_trials')
              field: id
        constraints:
          - type: not_null
          - type: primary_key

  - name: misc_info_module
    description: "Miscellaneous information module"
    config:
      contract:
        enforced: false
    columns:
      - name: id
        data_type: string
        description: "The primary key for this table"
        data_tests:
          - not_null
          - unique
          - relationships:
              to: ref('clinical_trials')
              field: id
        constraints:
          - type: not_null
          - type: primary_key


  - name: references
    description: "References for the clinical trial data"
    config:
      contract:
        enforced: false
    columns:
      - name: id
        data_type: string
        description: "The primary key for this table"
        data_tests:
          - not_null
          - unique
          - relationships:
              to: ref('clinical_trials')
              field: id
        constraints:
          - type: not_null
          - type: primary_key


  - name: arms_interventions
    description: "Interventions and arms of the clinical trials"
    config:
      contract:
        enforced: false
    columns:
      - name: id
        data_type: string
        description: "The primary key for this table"
        data_tests:
          - not_null
          - unique
          - relationships:
              to: ref('clinical_trials')
              field: id
        constraints:
          - type: not_null
          - type: primary_key


  - name: contacts_locations
    description: "Contact information and locations related to the trials"
    config:
      contract:
        enforced: false
    columns:
      - name: id
        data_type: string
        description: "The primary key for this table"
        data_tests:
          - not_null
          - unique
          - relationships:
              to: ref('clinical_trials')
              field: id
        constraints:
          - type: not_null
          - type: primary_key


  - name: info
    description: "General information about the trials"
    config:
      contract:
        enforced: false
    columns:
      - name: id
        data_type: string
        description: "The primary key for this table"
        data_tests:
          - not_null
          - unique
          - relationships:
              to: ref('clinical_trials')
              field: id
        constraints:
          - type: not_null
          - type: primary_key


  - name: outcome_measures
    description: "Measures of outcomes in clinical trials"
    config:
      contract:
        enforced: false
    columns:
      - name: id
        data_type: string
        description: "The primary key for this table"
        data_tests:
          - not_null
          - unique
          - relationships:
              to: ref('clinical_trials')
              field: id
        constraints:
          - type: not_null
          - type: primary_key


  - name: baseline_characteristics
    description: "Baseline characteristics of participants"
    config:
      contract:
        enforced: false
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - not_null
          - unique
          - relationships:
              to: ref('clinical_trials')
              field: id
        constraints:
          - type: not_null
          - type: primary_key


  - name: description
    description: "Descriptions of clinical trials"
    config:
      contract:
        enforced: false
    columns:
      - name: id
        data_type: string
        description: "The primary key for this table"
        data_tests:
          - not_null
          - unique
          - relationships:
              to: ref('clinical_trials')
              field: id
        constraints:
          - type: not_null
          - type: primary_key


  - name: intervention_browse
    description: "Browseable interventions in clinical trials"
    config:
      contract:
        enforced: false
    columns:
      - name: id
        data_type: string
        description: "The primary key for this table"
        data_tests:
          - not_null
          - unique
          - relationships:
              to: ref('clinical_trials')
              field: id
        constraints:
          - type: not_null
          - type: primary_key


  - name: outcomes
    description: "Outcomes of the clinical trials"
    config:
      contract:
        enforced: false
    columns:
      - name: id
        data_type: string
        description: "The primary key for this table"
        data_tests:
          - not_null
          - unique
          - relationships:
              to: ref('clinical_trials')
              field: id
        constraints:
          - type: not_null
          - type: primary_key


  - name: sponsor_collaborators
    description: "Sponsors and collaborators in the clinical trials"
    config:
      contract:
        enforced: false
    columns:
      - name: id
        data_type: string
        description: "The primary key for this table"
        data_tests:
          - not_null
          - unique
          - relationships:
              to: ref('clinical_trials')
              field: id
        constraints:
          - type: not_null
          - type: primary_key


  - name: design
    description: "Design details of the clinical trials"
    config:
      contract:
        enforced: false
    columns:
      - name: id
        data_type: string
        description: "The primary key for this table"
        data_tests:
          - not_null
          - unique
          - relationships:
              to: ref('clinical_trials')
              field: id
        constraints:
          - type: not_null
          - type: primary_key


  - name: ipd_sharing_statement
    description: "Statement on individual participant data sharing"
    config:
      contract:
        enforced: false
    columns:
      - name: id
        data_type: string
        description: "The primary key for this table"
        data_tests:
          - not_null
          - unique
          - relationships:
              to: ref('clinical_trials')
              field: id
        constraints:
          - type: not_null
          - type: primary_key


  - name: oversight
    description: "Oversight details for the clinical trials"
    config:
      contract:
        enforced: false
    columns:
      - name: id
        data_type: string
        description: "The primary key for this table"
        data_tests:
          - not_null
          - unique
          - relationships:
              to: ref('clinical_trials')
              field: id
        constraints:
          - type: not_null
          - type: primary_key


  - name: status
    description: "Status of the clinical trials"
    config:
      contract:
        enforced: false
    columns:
      - name: id
        data_type: string
        description: "The primary key for this table"
        data_tests:
          - not_null
          - unique
          - relationships:
              to: ref('clinical_trials')
              field: id
        constraints:
          - type: not_null
          - type: primary_key