name: Clinical Trials pipeline

on:
  push:
    branches: [ "dev", "main" ]
  pull_request:
    branches: [ "dev", "main" ]

env:
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

jobs:

  dev-tasks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Install dependencies
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install requirements
        run: pip install -r requirements.txt

      # Run flake8 for linting
      - name: Run flake8
        run: flake8

      # Run dbt compile
      - name: Run dbt compile
        run: cd clinicaltrials_dbt && dbt compile

      # Run in test mode (10 queries)
      - name: Run pipeline in test mode
        run: python pipeline.py --flag

      # Run dbt test
      - name: Run dbt test
        run: cd clinicaltrials_dbt && dbt test

      # Upload database as an artifact
      - name: Upload database as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: database.duckdb
          path: database.duckdb

  main-tasks:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Build the Docker image
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{ github.repository }}:$(date +%s)
